- name: Install required packages
  package:
    name: "{{ app_packages }}"
    state: present

- name: Open firewall for HTTP
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: Allow httpd to connect to DB (SELinux)
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db

- name: Enable and start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: Secure httpd for MediaWiki
  template:
    src: secure-mediawiki.conf.j2
    dest: /etc/httpd/conf.d/secure-mediawiki.conf
  notify: Restart httpd

- name: Download MediaWiki package
  get_url:
    url: "{{ package_link }}"
    dest: /tmp/mediawiki.tar.gz

- name: Unpack MediaWiki package
  unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: "{{ install_dir }}"
    remote_src: yes
    extra_opts: --strip-components=1

- name: Remove MediaWiki package
  file:
    path: /tmp/mediawiki.tar.gz
    state: absent
