- name: Install required packages
  package:
    name: "{{ app_packages }}"
    state: present

- name: Open firewall for HTTP
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: Enable and start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: Download MediaWiki package
  get_url:
    url: "{{ package_link }}"
    dest: /tmp/mediawiki.tar.gz

- name: Unpack MediaWiki package
  unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: --strip-components=1

- name: Remove MediaWiki package
  file:
    path: /tmp/mediawiki.tar.gz
    state: absent
