- name: Ensure {{ backup_script_location }} exists
  file:
    path: "{{ backup_script_location }}"
    state: directory

- name: Install backup script
  template:
    src: backup.sh.j2
    dest: "{{ backup_script_location }}/backup.sh"
    mode: '0774'
