- name: Install MariaDB packages
  package:
    name: "{{ database_packages }}"
    state: present
- name: Start and enable database service
  service:
    name: "{{ database_service }}"
    state: started
    enabled: true
- name: Secure MariaDB installation
  expect:
    command: mariadb-secure-installation
    responses:
      'Enter current password for root': ''
      'Switch to unix_socket authentication': 'n'
      'Change the root password?': 'y'
      'New password:': '{{ database_root_password }}'
      'Re-enter new password:': '{{ database_root_password }}'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database and access to it': 'y'
      'Reload privilege tables now': 'y'
    timeout: 5
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb.stdout_lines"
- name: Create database for MediaWiki
  mysql_db:
    name: "{{ database_name }}"
    state: present
    login_user: root
    login_password: "{{ database_root_password }}"
- name: Create database user for MediaWiki
  mysql_user:
    name: "{{ database_user }}"
    state: present
    password: "{{ database_password }}"
    host: "{{ app_server }}"
    priv: "{{ database_name }}.*: ALL,GRANT"
    login_user: root
    login_password: "{{ database_root_password }}"
    column_case_sensitive: false
- name: Open firewall for MariaDB
  firewalld:
    service: mysql
    state: enabled
    permanent: true
    immediate: true
