- name: Install MariaDB packages
  package:
    name: "{{ database_packages }}"
    state: present
- name: Start and enable database service
  service:
    name: "{{ database_service }}"
    state: started
    enabled: true
- name: Secure MariaDB installation
  expect:
    command: mariadb-secure-installation
    responses:
      'Enter current password for root': ''
      'Switch to unix_socket authentication': 'n'
      'Change the root password?': 'y'
      'New password:': '{{ database_root_password }}'
      'Re-enter new password:': '{{ database_root_password }}'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database and access to it': 'y'
      'Reload privilege tables now': 'y'
    timeout: 5
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb.stdout_lines"
