---
- name: Install and configure database
  hosts: db
  vars_files:
    - vars/database-vars.yml
  tasks:
    - name: Include tasks
      include_tasks: tasks/database-tasks.yml


- name: Configure the application server
  hosts: app
  vars_files:
    - vars/app-vars.yml
  tasks:
    - name: Include tasks
      include_tasks: tasks/app-tasks.yml
...
